version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/packages/core"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/packages/imagebits"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/apps/web"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
